# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e540c9999dd8f3f55fae2e18adc95ec9e404e3fcd0ddfed6dfffc9d424651375ce08898818e4d19eca000eea00f1602abdbd822fab96abe8a518c1493ffbd05

test:
  secret_key_base: ecdab5e81fc24f0b2fa51ce6d47b23c45a587671b14988c941ef73bb8454c65a70a25b203128bfa641cc1cec9fe33dd35973b47b00ee94671b878fdd8445ea5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
